name = "movie-night"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "movie-night-db"
database_id = "9886a10c-ce58-45d5-9ac0-378595bfbeb1"
migrations_dir = "drizzle/migrations"
